FORMAT = {
    # === Non-DASH ===
    '5': {'container': 'flv',
          'title': '240p',
          'sort': [240, 0],
          'video': {'height': 240, 'encoding': 'h.263'},
          'audio': {'bitrate': 64, 'encoding': 'mp3'}},
    '6': {'container': 'flv',  # Discontinued
          'discontinued': True,
          'video': {'height': 270, 'encoding': 'h.263'},
          'audio': {'bitrate': 64, 'encoding': 'mp3'}},
    '13': {'container': '3gp',  # Discontinued
           'discontinued': True,
           'video': {'encoding': 'mpeg-4'},
           'audio': {'encoding': 'aac'}},
    '17': {'container': '3gp',
           'title': '144p',
           'sort': [144, -20],
           'video': {'height': 144, 'encoding': 'mpeg-4'},
           'audio': {'bitrate': 24, 'encoding': 'aac'}},
    '18': {'container': 'mp4',
           'title': '360p',
           'sort': [360, 0],
           'video': {'height': 360, 'encoding': 'h.264'},
           'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '22': {'container': 'mp4',
           'title': '720p',
           'sort': [720, 0],
           'video': {'height': 720, 'encoding': 'h.264'},
           'audio': {'bitrate': 192, 'encoding': 'aac'}},
    '34': {'container': 'flv',  # Discontinued
           'discontinued': True,
           'video': {'height': 360, 'encoding': 'h.264'},
           'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '35': {'container': 'flv',  # Discontinued
           'discontinued': True,
           'video': {'height': 480, 'encoding': 'h.264'},
           'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '36': {'container': '3gp',
           'title': '240p',
           'sort': [240, -20],
           'video': {'height': 240, 'encoding': 'mpeg-4'},
           'audio': {'bitrate': 32, 'encoding': 'aac'}},
    '37': {'container': 'mp4',
           'title': '1080p',
           'sort': [1080, 0],
           'video': {'height': 1080, 'encoding': 'h.264'},
           'audio': {'bitrate': 192, 'encoding': 'aac'}},
    '38': {'container': 'mp4',
           'title': '3072p',
           'sort': [3072, 0],
           'video': {'height': 3072, 'encoding': 'h.264'},
           'audio': {'bitrate': 192, 'encoding': 'aac'}},
    '43': {'container': 'webm',
           'title': '360p',
           'sort': [360, -1],
           'video': {'height': 360, 'encoding': 'vp8'},
           'audio': {'bitrate': 128, 'encoding': 'vorbis'}},
    '44': {'container': 'webm',  # Discontinued
           'discontinued': True,
           'video': {'height': 480, 'encoding': 'vp8'},
           'audio': {'bitrate': 128, 'encoding': 'vorbis'}},
    '45': {'container': 'webm',  # Discontinued
           'discontinued': True,
           'video': {'height': 720, 'encoding': 'vp8'},
           'audio': {'bitrate': 192, 'encoding': 'vorbis'}},
    '46': {'container': 'webm',  # Discontinued
           'discontinued': True,
           'video': {'height': 1080, 'encoding': 'vp8'},
           'audio': {'bitrate': 192, 'encoding': 'vorbis'}},
    '59': {'container': 'mp4',
           'title': '480p',
           'sort': [480, 0],
           'video': {'height': 480, 'encoding': 'h.264'},
           'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '78': {'container': 'mp4',
           'title': '360p',
           'sort': [360, 0],
           'video': {'height': 360, 'encoding': 'h.264'},
           'audio': {'bitrate': 96, 'encoding': 'aac'}},
    # === 3D ===
    '82': {'container': 'mp4',
           '3D': True,
           'title': '3D@360p',
           'sort': [360, 0],
           'video': {'height': 360, 'encoding': 'h.264'},
           'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '83': {'container': 'mp4',
           '3D': True,
           'title': '3D@240p',
           'sort': [240, 0],
           'video': {'height': 240, 'encoding': 'h.264'},
           'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '84': {'container': 'mp4',
           '3D': True,
           'title': '3D@720p',
           'sort': [720, 0],
           'video': {'height': 720, 'encoding': 'h.264'},
           'audio': {'bitrate': 192, 'encoding': 'aac'}},
    '85': {'container': 'mp4',
           '3D': True,
           'title': '3D@1080p',
           'sort': [1080, 0],
           'video': {'height': 1080, 'encoding': 'h.264'},
           'audio': {'bitrate': 192, 'encoding': 'aac'}},
    '100': {'container': 'webm',
            '3D': True,
            'title': '3D@360p',
            'sort': [360, -1],
            'video': {'height': 360, 'encoding': 'vp8'},
            'audio': {'bitrate': 128, 'encoding': 'vorbis'}},
    '101': {'container': 'webm',  # Discontinued
            'discontinued': True,
            '3D': True,
            'title': '3D@360p',
            'sort': [360, -1],
            'video': {'height': 360, 'encoding': 'vp8'},
            'audio': {'bitrate': 192, 'encoding': 'vorbis'}},
    '102': {'container': 'webm',  # Discontinued
            'discontinued': True,
            '3D': True,
            'video': {'height': 720, 'encoding': 'vp8'},
            'audio': {'bitrate': 192, 'encoding': 'vorbis'}},
    # === Live Streams ===
    '91': {'container': 'ts',
           'Live': True,
           'title': 'Live@144p',
           'sort': [144, 0],
           'video': {'height': 144, 'encoding': 'h.264'},
           'audio': {'bitrate': 48, 'encoding': 'aac'}},
    '92': {'container': 'ts',
           'Live': True,
           'title': 'Live@240p',
           'sort': [240, 0],
           'video': {'height': 240, 'encoding': 'h.264'},
           'audio': {'bitrate': 48, 'encoding': 'aac'}},
    '93': {'container': 'ts',
           'Live': True,
           'title': 'Live@360p',
           'sort': [360, 0],
           'video': {'height': 360, 'encoding': 'h.264'},
           'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '94': {'container': 'ts',
           'Live': True,
           'title': 'Live@480p',
           'sort': [480, 0],
           'video': {'height': 480, 'encoding': 'h.264'},
           'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '95': {'container': 'ts',
           'Live': True,
           'title': 'Live@720p',
           'sort': [720, 0],
           'video': {'height': 720, 'encoding': 'h.264'},
           'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '96': {'container': 'ts',
           'Live': True,
           'title': 'Live@1080p',
           'sort': [1080, 0],
           'video': {'height': 1080, 'encoding': 'h.264'},
           'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '120': {'container': 'flv',  # Discontinued
            'discontinued': True,
            'Live': True,
            'title': 'Live@720p',
            'sort': [720, -10],
            'video': {'height': 720, 'encoding': 'h.264'},
            'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '127': {'container': 'ts',
            'Live': True,
            'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '128': {'container': 'ts',
            'Live': True,
            'audio': {'bitrate': 96, 'encoding': 'aac'}},
    '132': {'container': 'ts',
            'Live': True,
            'title': 'Live@240p',
            'sort': [240, 0],
            'video': {'height': 240, 'encoding': 'h.264'},
            'audio': {'bitrate': 48, 'encoding': 'aac'}},
    '151': {'container': 'ts',
            'Live': True,
            'title': 'Live@72p',
            'sort': [72, 0],
            'video': {'height': 72, 'encoding': 'h.264'},
            'audio': {'bitrate': 24, 'encoding': 'aac'}},
    # === DASH (video only)
    '133': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 240, 'encoding': 'h.264'}},
    '134': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 360, 'encoding': 'h.264'}},
    '135': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 480, 'encoding': 'h.264'}},
    '136': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 720, 'encoding': 'h.264'}},
    '137': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 1080, 'encoding': 'h.264'}},
    '138': {'container': 'mp4',  # Discontinued
            'discontinued': True,
            'dash/video': True,
            'video': {'height': 2160, 'encoding': 'h.264'}},
    '160': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 144, 'encoding': 'h.264'}},
    '167': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 360, 'encoding': 'vp8'}},
    '168': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 480, 'encoding': 'vp8'}},
    '169': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 720, 'encoding': 'vp8'}},
    '170': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 1080, 'encoding': 'vp8'}},
    '218': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 480, 'encoding': 'vp8'}},
    '219': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 480, 'encoding': 'vp8'}},
    '242': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 240, 'encoding': 'vp9'}},
    '243': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 360, 'encoding': 'vp9'}},
    '244': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 480, 'encoding': 'vp9'}},
    '247': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 720, 'encoding': 'vp9'}},
    '248': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 1080, 'encoding': 'vp9'}},
    '264': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 1440, 'encoding': 'h.264'}},
    '266': {'container': 'mp4',
            'dash/video': True,
            'video': {'height': 2160, 'encoding': 'h.264'}},
    '271': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 1440, 'encoding': 'vp9'}},
    '272': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 2160, 'encoding': 'vp9'}},
    '278': {'container': 'webm',
            'dash/video': True,
            'video': {'height': 144, 'encoding': 'vp9'}},
    '298': {'container': 'mp4',
            'dash/video': True,
            'fps': 60,
            'video': {'height': 720, 'encoding': 'h.264'}},
    '299': {'container': 'mp4',
            'dash/video': True,
            'fps': 60,
            'sort': [1080, 0],
            'video': {'height': 1080, 'encoding': 'h.264'}},
    '300': {'container': 'mp4',
            'dash/video': True,
            'fps': 60,
            'title': 'Live@720p',
            'sort': [720, 0],
            'video': {'height': 720, 'encoding': 'vp9'},
            'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '301': {'container': 'mp4',
            'dash/video': True,
            'fps': 60,
            'sort': [1080, 0],
            'title': 'Live@1080p',
            'video': {'height': 1080, 'encoding': 'h.264'},
            'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '302': {'container': 'webm',
            'dash/video': True,
            'fps': 60,
            'sort': [720, 0],
            'title': 'Live@720p',
            'video': {'height': 720, 'encoding': 'vp9'},
            'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '303': {'container': 'webm',
            'dash/video': True,
            'fps': 60,
            'title': 'Live@1080p',
            'sort': [1080, 0],
            'video': {'height': 1080, 'encoding': 'vp9'},
            'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '308': {'container': 'webm',
            'dash/video': True,
            'fps': 60,
            'title': 'Live@1440p',
            'sort': [1440, 0],
            'audio': {'bitrate': 256, 'encoding': 'aac'},
            'video': {'height': 1440, 'encoding': 'vp9'}},
    '313': {'container': 'webm',
            'dash/video': True,
            'title': 'Live@2160p',
            'audio': {'bitrate': 256, 'encoding': 'aac'},
            'sort': [2160, 0],
            'video': {'height': 2160, 'encoding': 'vp9'}},
    '315': {'container': 'webm',
            'dash/video': True,
            'fps': 60,
            'title': 'Live@2160p',
            'audio': {'bitrate': 256, 'encoding': 'aac'},
            'sort': [2160, 0],
            'video': {'height': 2160, 'encoding': 'vp9'}},
    # === Dash (audio only)
    '139': {'container': 'mp4',
            'dash/audio': True,
            'audio': {'bitrate': 48, 'encoding': 'aac'}},
    '140': {'container': 'mp4',
            'dash/audio': True,
            'audio': {'bitrate': 128, 'encoding': 'aac'}},
    '141': {'container': 'mp4',
            'dash/audio': True,
            'audio': {'bitrate': 256, 'encoding': 'aac'}},
    '171': {'container': 'webm',
            'dash/audio': True,
            'audio': {'bitrate': 128, 'encoding': 'vorbis'}},
    '172': {'container': 'webm',
            'dash/audio': True,
            'audio': {'bitrate': 192, 'encoding': 'vorbis'}},
    '249': {'container': 'webm',
            'dash/audio': True,
            'audio': {'bitrate': 50, 'encoding': 'opus'}},
    '250': {'container': 'webm',
            'dash/audio': True,
            'audio': {'bitrate': 70, 'encoding': 'opus'}},
    '251': {'container': 'webm',
            'dash/audio': True,
            'audio': {'bitrate': 160, 'encoding': 'opus'}},
    # === DASH adaptive
    '9999': {'container': 'mpd',
             'dash/audio': True,
             'dash/video': True,
             'audio': {'bitrate': 0, 'encoding': ''},
             'video': {'height': 0, 'encoding': ''}}
}

